/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2IAEf0CglP7
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import {Button} from "@/components/ui/button"
import {Label} from "@/components/ui/label"
import {Input} from "@/components/ui/input"
import {Textarea} from "@/components/ui/textarea"
import {useEffect, useState} from "react";
import {Endpoints} from "@/components/endpoints.tsx";

export function MainPage() {
    const [info, setInfo] = useState(null)

    useEffect(() => {
        fetch('/my_info.json')
            .then(response => response.json())
            .then(data => setInfo(data))
            .catch(error => console.error('Error fetching JSON:', error));
    }, []);

    if (!info) {
        return <div>Loading...</div>;
    }

    return (
        <div className="flex flex-col min-h-screen">
            <header className="bg-gray-900 text-white py-4 px-6 md:px-12">
                <div className="container mx-auto flex justify-between items-center">
                    <div className="text-2xl font-bold">{info.name}</div>
                    <nav className="hidden md:flex space-x-6">
                        <p className="hover:text-gray-400">
                            About
                        </p>
                        <p className="hover:text-gray-400">
                            Experience
                        </p>
                        <p className="hover:text-gray-400">
                            Education
                        </p>
                        <p className="hover:text-gray-400">
                            Skills
                        </p>
                        <p className="hover:text-gray-400">
                            Contact
                        </p>
                    </nav>
                    <Button className="md:hidden" size="sm" variant="outline">
                        <MenuIcon/>
                    </Button>
                </div>
            </header>
            <main className="flex-1">
                <section className="py-12 px-6 md:px-12" id="about">
                    <div className="container mx-auto max-w-4xl space-y-6">
                        <h2 className="text-3xl font-bold">About Me</h2>
                        <p className="text-gray-600 dark:text-gray-400">
                            {info.summary}
                        </p>
                    </div>
                </section>
                <section className="bg-gray-100 dark:bg-gray-800 py-12 px-6 md:px-12" id="experience">
                    <div className="container mx-auto max-w-4xl space-y-6">
                        <h2 className="text-3xl font-bold">Experience</h2>
                        <div className="space-y-8">
                            {info.experience.map((exp: string, index: number) => (
                                exp.show ? (
                                    <div key={index}>
                                        <h3 className="text-xl font-bold">{exp.title}</h3>
                                        <p className="text-gray-600 dark:text-gray-400">{exp.company} | {exp.startDate} - {exp.endDate}</p>
                                        <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
                                            {exp.responsibilities.map((responsibility: string, i: number) => (
                                                <li key={i}>{responsibility}</li>
                                            ))}
                                        </ul>
                                    </div>) : null
                            ))}
                        </div>
                    </div>
                </section>
                <section className="py-12 px-6 md:px-12" id="education">
                    <div className="container mx-auto max-w-4xl space-y-6">
                        <h2 className="text-3xl font-bold">Education</h2>
                        <div className="space-y-4">
                            {info.education.map((_edu: string, index: number) => (
                                <div key={index}>

                                    <h3 className="text-xl font-bold">{_edu.degree}</h3>
                                    <p className="text-gray-600 dark:text-gray-400">{_edu.institution}, {_edu.graduationYear}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </section>
                <section className="bg-gray-100 dark:bg-gray-800 py-12 px-6 md:px-12" id="skills">
                    <div className="container mx-auto max-w-4xl space-y-6">
                        <h2 className="text-3xl font-bold">Skills</h2>
                        <div className="grid grid-cols-2 md:grid-cols-3 gap-6">

                            {info.technicalSkills.map((category, index) => (
                                <div key={index} className="bg-white dark:bg-gray-900 rounded-lg p-4 shadow">
                                    {Object.entries(category).map(([skillCategory, skills]) => (
                                        <div key={skillCategory}>
                                            <h3 className="text-lg font-bold">{skillCategory}</h3>
                                            <div className="mt-4 space-y-2">
                                                {skills.map((skill, i) => (
                                                    <div key={i} className="flex items-center justify-between">
                                                        <span>{Object.keys(skill)[0]}</span>
                                                        <div
                                                            className="w-2/3 bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                                                            <div
                                                                className="bg-blue-500 h-2 rounded-full"
                                                                style={{
                                                                    width: `${Object.values(skill)[0]}%`,
                                                                }}
                                                            />
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            ))}
                        </div>
                    </div>
                </section>
                <section className="py-12 px-6 md:px-12" id="contact">
                    <div className="container mx-auto max-w-4xl space-y-6">
                        <h2 className="text-3xl font-bold">Contact</h2>
                        <form className="space-y-4">
                            <div>
                                <Label htmlFor="name">Name</Label>
                                <Input id="name" placeholder="John Doe" required type="text"/>
                            </div>
                            <div>
                                <Label htmlFor="email">Email</Label>
                                <Input id="email" placeholder="john@example.com" required type="email"/>
                            </div>
                            <div>
                                <Label htmlFor="message">Message</Label>
                                <Textarea id="message" placeholder="Your message..." required rows={5}/>
                            </div>
                            <Button className="w-full" type="submit">
                                Submit
                            </Button>
                        </form>
                    </div>
                </section>

                <section className="bg-gray-100 dark:bg-gray-800 py-12 px-6 md:px-12">
                    <div className="container mx-auto max-w-4xl space-y-6">
                        <Endpoints/>
                    </div>
                </section>
            </main>
            <footer className="bg-gray-900 text-white py-6 px-6 md:px-12">
                <div className="container mx-auto flex flex-col md:flex-row justify-between items-center">
                    <div className="text-sm">© 2024 {info.name}. All rights reserved.</div>
                    <div className="flex space-x-4 mt-4 md:mt-0">
                        <p className="hover:text-gray-400">
                            <GithubIcon/>
                        </p>
                        <p className="hover:text-gray-400">
                            <LinkedinIcon/>
                        </p>
                        <p className="hover:text-gray-400">
                            <TwitterIcon/>
                        </p>
                    </div>
                </div>
            </footer>
        </div>
    )
}

function GithubIcon() {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path
                d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/>
            <path d="M9 18c-4.51 2-5-2-7-2"/>
        </svg>
    )
}


function LinkedinIcon() {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/>
            <rect width="4" height="12" x="2" y="9"/>
            <circle cx="4" cy="4" r="2"/>
        </svg>
    )
}


function MenuIcon() {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <line x1="4" x2="20" y1="12" y2="12"/>
            <line x1="4" x2="20" y1="6" y2="6"/>
            <line x1="4" x2="20" y1="18" y2="18"/>
        </svg>
    )
}


function TwitterIcon() {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path
                d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z"/>
        </svg>
    )
}
